myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'
urlpatterns = [
    # 曲
    # 一覧
    path('song/', views.song_list, name='song_list'),
    # 登録
    path('song/add/', views.song_edit, name='song_add'),
    # 修正
    path('song/mod/<int:song_id>/', views.song_edit, name='song_mod'),
    # 削除
    path('song/del/<int:song_id>/', views.song_del, name='song_del'),
    # 感想
    # 一覧
    path('comment/<int:song_id>/', views.CommentList.as_view(), name='comment_list'),
    # 登録
    path('comment/add/<int:song_id>/', views.comment_edit, name='comment_add'),
    # 修正
    path('comment/mod/<int:song_id>/<int:comment_id>/', views.comment_edit, name='comment_mod'),
    # 削除
    path('comment/del/<int:song_id>/<int:comment_id>', views.comment_del, name='comment_del'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # アプリのurl
    path('myapp/', include('myapp.urls')),
]

myapp/models.py
from django.db import models


class Song(models.Model):
    name = models.CharField('曲名', max_length=100)
    singer_name = models.CharField('歌手名', max_length=200)
    anime_title = models.CharField('アニメタイトル', max_length=100)

    def __str__(self):
        return self.name


class Comment(models.Model):
    song_name = models.ForeignKey(Song, verbose_name='曲名', related_name='comment', on_delete=models.CASCADE)
    comment = models.TextField('コメント', blank=True)

    def __str__(self):
        return self.comment

myapp/forms.py
from django.forms import ModelForm
from myapp.models import Song, Comment


class SongForm(ModelForm):
    """曲のフォーム"""
    class Meta:
        model = Song
        fields = ('name', 'singer_name', 'anime_title',)


class CommentForm(ModelForm):
    """コメントのフォーム"""
    class Meta:
        model = Comment
        fields = ('comment', )

myapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from myapp.models import Song, Comment
from myapp.forms import SongForm, CommentForm
from django.views.generic.list import ListView


def song_list(request):
    """曲の一覧表示"""
    songs = Song.objects.all().order_by('id')
    return render(request,
                  'myapp/song_list.html',  # 使用するテンプレート
                  {'songs': songs})         # テンプレートに渡すデータ


def song_edit(request, song_id=None):
    """曲の編集"""
    # song_idが指定されているなら修正、指定されていないなら追加
    if song_id:
        song = get_object_or_404(Song, pk=song_id)
    else:
        song = Song()
    # POSTされたrequestデータからフォームを作成
    if request.method == 'POST':
        form = SongForm(request.POST, instance=song)
        if form.is_valid():
            song = form.save(commit=False)
            song.save()
            return redirect('myapp:song_list')
        # GETの時
    else:
        # songインスタンスからフォームを作成
        form = SongForm(instance=song)
    return render(request, 'myapp/song_edit.html', dict(form=form, song_id=song_id))


def song_del(request, song_id):
    """曲の削除"""
    song = get_object_or_404(Song, pk=song_id)
    song.delete()
    return redirect('myapp:song_list')


class CommentList(ListView):
    """感想の一覧"""
    context_object_name = 'comments'
    template_name = 'myapp/comment_list.html'
    # 1ページは最大2件ずつでページングする
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        song = get_object_or_404(Song, pk=kwargs['song_id'])  # 親の曲を読む
        comment = song.comment.all().order_by('id')           # 曲の子供の、コメントを読む
        self.object_list = comment

        context = self.get_context_data(object_list=self.object_list, song=song)
        return self.render_to_response(context)


def comment_edit(request, song_id, comment_id=None):
    """コメントの編集"""
    song = get_object_or_404(Song, pk=song_id)  # 親の曲を読む
    # comment_idが指定されている（修正時）
    if comment_id:
        comment = get_object_or_404(Comment, pk=comment_id)
    # comment_idが指定されていない（追加時）
    else:
        comment = Comment()

    if request.method == 'POST':
        # POSTされたrequestデータからフォームを作成
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.song = song
            comment.save()
            return redirect('myapp:comment_list', song_id=song_id)
    else:  # GETの時
        form = CommentForm(instance=comment)

    return render(request, 'myapp/comment_edit.html', dict(form=form, song_id=song_id, comment_id=comment_id))


def comment_del(request, song_id, comment_id):
    """コメントの削除"""
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect('myapp:comment_list', song_id=song_id)

myapp/templates/myapp/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'myapp/css/bootstrap.min.css' %}">
{% block extra_css %}{% endblock %}
<title>{% block title %}My books{% endblock %}</title>
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
<script src="{% static 'myapp/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'myapp/js/bootstrap.bundle.min.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

myapp/templates/myapp/comment_edit.html
{% extends "myapp/base.html" %}
{% load bootstrap4 %}

{% block title %}コメントの編集{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">コメントの編集</h4>
    {% if comment_id %}
    <form action="{% url 'myapp:comment_mod' song_id=song_id comment_id=comment_id %}" method="post">
    {% else %}
    <form action="{% url 'myapp:comment_add' song_id=song_id %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'myapp:comment_list' song_id=song_id %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

myapp/templates/myapp/comment_list.html
{% extends "myapp/base.html" %}

{% block title %}コメントの一覧{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom">コメントの一覧 <small class="text-muted ml-3">{{ song.name }}</small></h4>
    <a href="{% url 'myapp:comment_add' song_id=song.id %}" class="btn btn-primary btn-sm my-3">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>曲名</th>
          <th>コメント</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for comment in comments %}
        <tr>
          <td>{{ comment.id }}</td>
          <td>{{ comment.song_name }}</td>
          <td>{{ comment.comment|linebreaksbr }}</td>
          <td>
            <a href="{% url 'myapp:comment_mod' song_id=song.id comment_id=comment.id %}" class="btn btn-outline-primary btn-sm">修正</a>
            <button class="btn btn-outline-danger btn-sm del_confirm" data-toggle="modal" data-target="#deleteModal" data-pk="{{ comment.id }}" data-url="{% url 'myapp:comment_del' song_id=song.id comment_id=comment.id %}">削除</button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if is_paginated %}
    <nav aria-label="Page navigation">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a></li>
        {% endif %}
        {% for linkpage in page_obj.paginator.page_range %}
          {% ifequal linkpage page_obj.number %}
            <li class="page-item active"><a class="page-link" href="#">{{ linkpage }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a></li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

    <a href="{% url 'myapp:song_list' %}" class="btn btn-secondary btn-sm">戻る</a>

    {# 削除を確認するモーダル ダイアログ #}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">確認</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
          <div class="modal-body">
            <p>ID: <span id="del_pk"></span> を削除しますか？</p>
          </div>
          <div class="modal-footer">
            <a href="#" class="btn btn-primary" id="del_url">OK</a>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

{% block extra_js %}
<script>
$(function() {
  $('.del_confirm').on('click', function () {
     $("#del_pk").text($(this).data("pk"));
     $('#del_url').attr('href', $(this).data("url"));
  });
});
</script>
{% endblock %}

myapp/templates/myapp/song_edit.html
{% extends "myapp/base.html" %}
{% load bootstrap4 %}

{% block title %}曲の編集{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">曲の編集</h4>
    {% if book_id %}
    <form action="{% url 'myapp:song_mod' song_id=song_id %}" method="post">
    {% else %}
    <form action="{% url 'myapp:song_add' %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'myapp:song_list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

myapp/templates/myapp/song_list.html
{% extends "myapp/base.html" %}
{% block title %}曲の一覧{% endblock title %}
{% block content %}
    <h4 class="mt-4 border-bottom">曲の一覧</h4>
    <a href="{% url 'myapp:song_add' %}" class="btn btn-primary btn-sm my-3">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">曲名</th>
          <th scope="col">歌手名</th>
          <th scope="col">アニメタイトル</th>
          <th scope="col">操作</th>
        </tr>
      </thead>
      <tbody>
        {% for song in songs %}
        <tr>
          <th scope="row">{{ song.id }}</th>
          <td>{{ song.name }}</td>
          <td>{{ song.singer_name }}</td>
          <td>{{ song.anime_title }}</td>
          <td>
            <a href="{% url 'myapp:song_mod' song_id=song.id %}" class="btn btn-outline-primary btn-sm">修正</a>
            <a href="{% url 'myapp:song_del' song_id=song.id %}" class="btn btn-outline-danger btn-sm">削除</a>
            <a href="{% url 'myapp:comment_list' song_id=song.id %}" class="btn btn-outline-info btn-sm">感想の一覧</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock content %}